import { useEffect, useRef, useState, useCallback } from 'react';

export interface PriceTick {
  symbol: string;
  price: number;
  change_24h: number;
  high_24h: number;
  low_24h: number;
  volume: number;
  timestamp: string;
  _mock?: boolean;  // true when generated by fallback mock data (not from exchange)
}

// Dynamically determine WebSocket URL.
// Priority:
//   1. VITE_WS_URL — explicit WebSocket URL override
//   2. VITE_API_URL — derive WebSocket host + protocol from the API URL
//      (e.g. http://localhost:8000 → ws://localhost:8000, https://... → wss://...)
//   3. Same origin — works in production (Railway serves API + dashboard together)
const WS_URL = import.meta.env.VITE_WS_URL ?? (() => {
  const apiUrl = import.meta.env.VITE_API_URL;
  if (apiUrl) {
    const parsed = new URL(apiUrl);
    const wsProto = parsed.protocol === 'https:' ? 'wss:' : 'ws:';
    return `${wsProto}//${parsed.host}/ws/prices`;
  }
  const wsProto = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
  return `${wsProto}//${window.location.host}/ws/prices`;
})();
const RECONNECT_DELAY = 3000;
const MAX_RECONNECT_ATTEMPTS = 10;

// ── Fallback mock data generator (when WebSocket is unreachable) ──────
// Mock data is deliberately artificial so it's visually distinguishable
// from real price data. Prices use round numbers with slow, step-wise
// movement and fixed 24h change to avoid misleading users.

const FALLBACK_SYMBOLS = ['ETHUSDT'];
const FALLBACK_BASE: Record<string, number> = {
  ETHUSDT: 1800,
};

function generateMockTick(prices: Record<string, number>): PriceTick {
  // Generate mock ETH price with slow drift
  const symbol = FALLBACK_SYMBOLS[0];
  const base = prices[symbol] ?? FALLBACK_BASE[symbol];
  const drift = base * (Math.random() - 0.5) * 0.0004;
  const roundTo = 1;
  const newPrice = Math.round((base + drift) / roundTo) * roundTo;
  prices[symbol] = newPrice;
  return {
    symbol,
    price: newPrice,
    change_24h: 0,  // No meaningful change in mock mode
    high_24h: newPrice,
    low_24h: newPrice,
    volume: 0,
    timestamp: new Date().toISOString(),
    _mock: true,  // flag for UI to show simulated indicator
  };
}

// ── Hook ────────────────────────────────────────────────────────────────

export function usePriceStream() {
  const [prices, setPrices] = useState<Record<string, PriceTick>>({});
  const [connected, setConnected] = useState(false);
  const wsRef = useRef<WebSocket | null>(null);
  const reconnectAttempt = useRef(0);
  const reconnectTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const mockTimer = useRef<ReturnType<typeof setInterval> | null>(null);
  const connectRef = useRef<() => void>(undefined);
  const fallbackPrices = useRef<Record<string, number>>({ ...FALLBACK_BASE });

  const cleanup = useCallback(() => {
    if (wsRef.current) {
      wsRef.current.onclose = null;
      wsRef.current.onerror = null;
      wsRef.current.onmessage = null;
      wsRef.current.close();
      wsRef.current = null;
    }
    if (reconnectTimer.current) {
      clearTimeout(reconnectTimer.current);
      reconnectTimer.current = null;
    }
    if (mockTimer.current) {
      clearInterval(mockTimer.current);
      mockTimer.current = null;
    }
  }, []);

  const startMockFallback = useCallback(() => {
    if (mockTimer.current) return;
    setConnected(false);
    FALLBACK_SYMBOLS.forEach(s => {
      fallbackPrices.current[s] = FALLBACK_BASE[s];
    });
    mockTimer.current = setInterval(() => {
      const tick = generateMockTick(fallbackPrices.current);
      setPrices(prev => ({ ...prev, [tick.symbol]: tick }));
    }, 1500);
  }, []);

  const connect = useCallback(() => {
    cleanup();

    try {
      const ws = new WebSocket(WS_URL);
      wsRef.current = ws;

      ws.onopen = () => {
        setConnected(true);
        reconnectAttempt.current = 0;
      };

      ws.onmessage = (event) => {
        try {
          const tick: PriceTick = JSON.parse(event.data);
          setPrices(prev => ({ ...prev, [tick.symbol]: tick }));
        } catch {
          // Malformed message — skip
        }
      };

      ws.onclose = () => {
        setConnected(false);
        wsRef.current = null;
        if (reconnectAttempt.current < MAX_RECONNECT_ATTEMPTS) {
          reconnectAttempt.current += 1;
          const delay = RECONNECT_DELAY * Math.min(reconnectAttempt.current, 5);
          reconnectTimer.current = setTimeout(() => connectRef.current?.(), delay);
        } else {
          startMockFallback();
        }
      };

      ws.onerror = () => {
        ws.close();
      };
    } catch {
      startMockFallback();
    }
  }, [cleanup, startMockFallback]);

  useEffect(() => {
    // Keep connectRef synced so the onclose closure always calls the latest connect
    connectRef.current = connect;
  });

  useEffect(() => {
    connect();
    return cleanup;
  }, [connect, cleanup]);

  return { prices, connected };
}
